services:
    freelance-hq:
        container_name: freelance-hq
        image: ghcr.io/makkenzo/freelance-hq:latest
        restart: always
        env_file:
            - .env
        ports:
            - 22742:3000
